### ISSUE TITLE
strange permission problem with Sams?

### ISSUE THREAD

**Issue by RiesBen** [OpenFreeEnergy/openfe#170]
Hi @IAlibay ,
 my SAMS runs did die after this error (seems to be in the finalization stage?): 

PermissionError: [Errno 13] Permission denied: '/lig_p38a_3flw_lig_p38a_3fly_rep0_complex_real_time_analysis.yaml'
CRITICAL:mpiplus.mpiplus:MPI node 1/1 raised an exception and called Abort()! The exception traceback follows

Traceback (most recent call last):
  File "path/Experiments/free_energies/src/scripts/run_system_sams.py", line 100, in <module>
    complex_transform.run(dry=False, verbose=True)
  File "path/openfe/openfe/setup/methods/openmm/equil_rbfe_methods.py", line 945, in run
    sampler.extend(int(prod_steps.m / mc_steps))  # type: ignore
  File "path/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistatesampler.py", line 821, in extend
    self.run(n_iterations)
  File "path/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistatesampler.py", line 787, in run
    self._update_analysis()
  File "path/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistatesampler.py", line 1661, in _update_analysis
    self._last_err_free_energy = self._offline_analysis()
  File "path/miniconda3/envs/openfe/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 271, in _wrapper
    return run_single_node(rank, task, *args, **kwargs)
  File "path/miniconda3/envs/openfe/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 220, in run_single_node
    result = task(*args, **kwargs)
  File "path/miniconda3/envs/openfe/lib/python3.9/site-packages/mpiplus/mpiplus.py", line 621, in _delayed_termination
    return func(*args, **kwargs)
  File "path/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/utils.py", line 94, in _wrapper
    return func(*args, **kwargs)
  File "path/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistatesampler.py", line 1587, in _offline_analysis
    self._reporter.write_current_statistics(data_dict)
  File "path/miniconda3/envs/openfe/lib/python3.9/site-packages/openmmtools/multistate/multistatereporter.py", line 1341, in write_current_statistics
    with open(output_filepath, "a") as out_file:
PermissionError: [Errno 13] Permission denied: '/lig_p38a_3flw_lig_p38a_3fly_rep0_complex_real_time_analysis.yaml'

**Comment by IAlibay** [comment]
@RiesBen can you re-run adding a "./" before the output and checkpoint file names?

**Comment by RiesBen** [comment]
Trying this. But this seems to me like behavior we might want to avoid?

**Comment by IAlibay** [comment]
yeah we'll need to push for change upstream

**Comment by mikemhenry** [comment]
Please open bug reports for `openmmtools`! I've got write access their so we can get things fixed

**Comment by RiesBen** [comment]
@mikemhenry  Hi, I raised an issue, sorry was quite busy past weeks. Hope it helps? :)

**Comment by RiesBen** [comment]
I think next we can close this issue :)

**Comment by mikemhenry** [comment]
Fixed with https://github.com/choderalab/openmmtools/pull/616
