### ISSUE TITLE
RelativeHybridTopologyProtocolSettings can not round trip to JSON

### ISSUE THREAD

**Issue by jthorton** [OpenFreeEnergy/openfe#518]
I want to be able to save the `RelativeHybridTopologyProtocolSettings` object to a JSON file to track the settings used in my calculations however I get validation errors when trying to parse the file, see the example below. I think part of the problem is the general settings types used on the base [Settings class](https://github.com/OpenFreeEnergy/gufe/blob/799b5b23563d6e259f187c857ae110a991601b01/gufe/settings/models.py#L95). The other part of the issue seems to be related to the fact that [openff-models can not parse units on nested models correctly](https://github.com/openforcefield/openff-models/issues/8#issuecomment-1266686638). 

```python
from openfe.protocols.openmm_rfe.equil_rfe_settings import RelativeHybridTopologyProtocolSettings
from openfe.protocols.openmm_rfe import RelativeHybridTopologyProtocol


print("Creating settings from raw json")
s2 = RelativeHybridTopologyProtocolSettings.parse_raw(settings.json(indent=2))
```
> Creating settings from raw json
Traceback (most recent call last):
  File "/Users/joshua/Documents/Projects/ASAP/software_dev/openfe_workflow/test_alchemiscale/test_openfe.py", line 8, in <module>
    s2 = RelativeHybridTopologyProtocolSettings.parse_raw(settings.json(indent=2))
  File "pydantic/main.py", line 549, in pydantic.main.BaseModel.parse_raw
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 18 validation errors for RelativeHybridTopologyProtocolSettings
forcefield_settings -> constraints
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> forcefields
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> hydrogen_mass
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> remove_com
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> rigid_water
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> small_molecule_forcefield
  extra fields not permitted (type=value_error.extra)
thermo_settings -> temperature
  Cannot convert from 'dimensionless' (dimensionless) to 'kelvin' ([temperature]) (type=type_error.dimensionality; units1=dimensionless; units2=kelvin; dim1=dimensionless; dim2=[temperature]; extra_msg=)
thermo_settings -> pressure
  Cannot convert from 'dimensionless' (dimensionless) to 'standard_atmosphere' ([mass] / [length] / [time] ** 2) (type=type_error.dimensionality; units1=dimensionless; units2=standard_atmosphere; dim1=dimensionless; dim2=[mass] / [length] / [time] ** 2; extra_msg=)
system_settings -> nonbonded_cutoff
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)
solvation_settings -> solvent_padding
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)
alchemical_sampler_settings -> online_analysis_target_error
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)
integrator_settings -> timestep
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)
integrator_settings -> collision_rate
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)
integrator_settings -> n_steps
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)
integrator_settings -> barostat_frequency
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)
simulation_settings -> equilibration_length
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)
simulation_settings -> production_length
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)
simulation_settings -> checkpoint_interval
  instance of Quantity expected (type=type_error.arbitrary_type; expected_arbitrary_type=Quantity)

**Comment by jthorton** [comment]
Thanks for the pointer @dwhswenson, I was using the standard pydantic to and from JSON methods (see the code in the issue) but it seems like the `JSON_HANDLER.decoder` is needed to parse these nested models with quantities correctly. Once I have the dict however I still can not reconstruct the `RelativeHybridTopologyProtocolSettings` as the type hint for the forcefield uses the general base class. See the new example below.

```python
from openfe.protocols.openmm_rfe.equil_rfe_settings import RelativeHybridTopologyProtocolSettings
from openfe.protocols.openmm_rfe import RelativeHybridTopologyProtocol
import json
from gufe.tokenization import JSON_HANDLER

settings = RelativeHybridTopologyProtocol.default_settings()

print("saving to file")
with open("settings.json", mode='w') as f:
    json.dump(settings.dict(), f, cls=JSON_HANDLER.encoder)

with open("settings.json", mode='r') as f:
    obj = json.load(f, cls=JSON_HANDLER.decoder)
print(type(obj))
s2 = RelativeHybridTopologyProtocolSettings(**obj)
```
> saving to file
<class 'dict'>
Traceback (most recent call last):
  File "/Users/joshua/Documents/Projects/ASAP/software_dev/openfe_workflow/test_alchemiscale/test_openfe.py", line 17, in <module>
    s2 = RelativeHybridTopologyProtocolSettings(**obj)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 6 validation errors for RelativeHybridTopologyProtocolSettings
forcefield_settings -> constraints
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> forcefields
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> hydrogen_mass
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> remove_com
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> rigid_water
  extra fields not permitted (type=value_error.extra)
forcefield_settings -> small_molecule_forcefield
  extra fields not permitted (type=value_error.extra)

**Comment by richardjgowers** [comment]
@jthorton hmm yes that's annoying.  For now, the code below works, you don't need to (but arguably should be able to) convert the settings to a dict to serialise it.

```python
import gufe
import openfe
import json

from openfe.protocols import openmm_rfe

s = openmm_rfe.RelativeHybridTopologyProtocol.default_settings()

s_string = json.dumps(s, cls=gufe.tokenization.JSON_HANDLER.encoder)

s2 = json.loads(s_string, cls=gufe.tokenization.JSON_HANDLER.decoder)

```
