### ISSUE TITLE
Error using quickrun on 1.0.0rc0

### ISSUE THREAD

**Issue by jbluck** [OpenFreeEnergy/openfe#756]
I know it is early days, but I thought it would be helpful to report that I get the following error using the TYK2 example inputs on the `1.0.0rc0` code pulled on Monday, both on a local installation and on an HPC. 

I installed the release using the instructions on the GitHub README. Please let me know if you need an example JSON file. 

```
Planning simulations for this edge...
Traceback (most recent call last):
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/bin/openfe", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/openfecli/utils.py", line 110, in wrapper
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/openfecli/commands/quickrun.py", line 101, in quickrun
    dag = trans.create()
          ^^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/gufe/transformations/transformation.py", line 124, in create
    return self.protocol.create(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/gufe/protocols/protocol.py", line 224, in create
    protocol_units=self._create(
                   ^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/openfe/protocols/openmm_rfe/equil_rfe_methods.py", line 490, in _create
    _validate_alchemical_components(alchem_comps, mapping)
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/openfe/protocols/openmm_rfe/equil_rfe_methods.py", line 217, in _validate_alchemical_components
    mapped = {'stateA': [m.componentA for m in mapping],
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/XXXX/mambaforge/envs/openfe_1_0_0_rc0/lib/python3.11/site-packages/openfe/protocols/openmm_rfe/equil_rfe_methods.py", line 217, in <listcomp>
    mapped = {'stateA': [m.componentA for m in mapping],
                         ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'componentA'
```

**Comment by richardjgowers** [comment]
@jbluck I'm having a little trouble reproducing this locally.  At a first glance, it looks like there's a mix of new and old code there giving that error.

I'm building the rc environment with this command:

`mamba create -n openfe_rc -c conda-forge/label/openfe_rc -c conda-forge/label/gufe_rc -c conda-forge openfe`

where the `-c` argument has more than usual to pick up the rc-versioned packages

This should then mean that running `conda list openfe` and `conda list gufe` to report the version numbers gives something like below:
```
    ~/tes/rc/a/transformations  conda list openfe                                                          1 ✘  24s   openfe_rc  
# packages in environment at /home/richard/miniconda3/envs/openfe_rc:
#
# Name                    Version                   Build  Channel
openfe                    1.0.0rc0           pyhcd8161a_0    conda-forge/label/openfe_rc
openfe-analysis           0.2.0              pyhd8ed1ab_0    conda-forge
    ~/tes/rc/a/transformations  conda list gufe                                                                      ✔  openfe_rc  
# packages in environment at /home/richard/miniconda3/envs/openfe_rc:
#
# Name                    Version                   Build  Channel
gufe                      1.0.0rc0           pyhdbea692_0    conda-forge/label/gufe_rc
```

Can you double check what `conda list` is giving you to check that the env you've built is sane?

**Comment by richardjgowers** [comment]
And as a second thought, can you double check that both the head (running plan) and compute (running quickrun) halves of this process are using the same (new) conda env?

**Comment by jbluck** [comment]
For added context, before I was doing:

```
git clone https://github.com/OpenFreeEnergy/openfe.git
cd openfe
mamba env create -f environment.yml
python -m pip install --no-deps .
```

which gave the following when listed:

```
 bash-4.4$ conda list openfe
# packages in environment at /XXXX/packages/mamba2023/envs/openfe_1_0_0rc0_2:
#
# Name                    Version                   Build  Channel
openfe                    1.0.0rc0           pyhcd8161a_0    conda-forge/label/openfe_rc
openfe-analysis           0.2.0              pyhd8ed1ab_0    conda-forge
 bash-4.4$ conda list gufe  
# packages in environment at /XXXX/packages/mamba2023/envs/openfe_1_0_0rc0_2:
#
# Name                    Version                   Build  Channel
gufe                      1.0.0rc0           pyhdbea692_0    conda-forge/label/gufe_rc
```


and now I am using your command:

`mamba create -n openfe_rc -c conda-forge/label/openfe_rc -c conda-forge/label/gufe_rc -c conda-forge openfe`

and listing gives:

```
bash-4.4$ conda list openfe
# packages in environment at /XXXX/packages/mamba2023/envs/openfe_1_0_0rc0_2:
#
# Name                    Version                   Build  Channel
openfe                    1.0.0rc0           pyhcd8161a_0    conda-forge/label/openfe_rc
openfe-analysis           0.2.0              pyhd8ed1ab_0    conda-forge
bash-4.4$ conda list gufe  
# packages in environment at /XXXX/packages/mamba2023/envs/openfe_1_0_0rc0_2:
#
# Name                    Version                   Build  Channel
gufe                      1.0.0rc0           pyhdbea692_0    conda-forge/label/gufe_rc
```


and so I am still getting the same error :( I am now running a CUDA Version of 12.2, so should not be the same issue I was having with openmm before.

**Comment by jbluck** [comment]
I am using identical commands (copy and paste) to build the environment on both my local workstation and on our HPC. They have the same mamba installation.

**Comment by IAlibay** [comment]
@jbluck just to clarify - which TYK2 example inputs are you running? Is it the ones from this tutorial https://github.com/OpenFreeEnergy/ExampleNotebooks/blob/main/rbfe_tutorial/cli_tutorial.md

**Comment by jbluck** [comment]
Yes, those inputs. I also used modified versions of these inputs and tried a totally different system, both gave the same error. 

I have emailed you an example JSON file.

**Comment by IAlibay** [comment]
@jbluck are you using a brand new generated JSON? From a quick look it seems like you've got something that's been defined using an older version of openfe.

**Comment by jbluck** [comment]
That JSON was generated a few hours ago, in my 1.0.0rc0 environment. Running ` which python` showas it was using the right paths.
